{% set name = "s1_orbits" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/s1_orbits-{{ version }}.tar.gz
  sha256: 5d33e5ec4a4d9576a5f1124852030ffb597641f896de732599a44aec3a733195

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.9
    - requests

test:
  imports:
    - s1_orbits
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ASFHyP3/sentinel1-orbits-py
  summary: A Python utility for downloading Sentinel-1 Orbit files from the Registry of Open Data on AWS
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AndrewPlayer3
    - jhkennedy
    - asjohnston-asf
    - jtherrmann
    - jacquelynsmale
    - forrestfwilliams
